<li><a href="#tabs-4">Notes</a></li>
<li><a href="#tabs-5">Annotations</a></li>
<li><a href="#tabs-6">Parameters</a></li>
<li><a href="#tabs-7">Reactions</a></li>
<li><a href="#tabs-8">Events</a></li>
<li><a href="#tabs-9">Maths</a></li>
<li><a href="#tabs-10">Function Definitions</a></li>
<li><a href="#tabs-11">Compartments</a></li>
<li><a href="#tabs-12">Species</a></li>
<li><a href="#tabs-13">Exports</a></li>
