package net.biomodels.jummp.webapp.remote

import net.biomodels.jummp.remote.RemoteModelAdapter

/**
 * @short Delegating Service to RemoteModelAdapter.
 *
 * Be aware: the methods are generated by the RemoteServiceTransformation!
 * Do not implement the methods of the RemoteModelAdapter!
 */
class RemoteModelService implements RemoteModelAdapter {

    static transactional = true
    @Delegate RemoteModelAdapter remoteModelAdapter
}
