package net.biomodels.jummp.webapp.remote

import net.biomodels.jummp.remote.RemoteUserAdapter

/**
 * @short Service delegating to RemoteUserAdapter.
 *
 * Be aware: the methods are generated by the RemoteServiceTransformation!
 * Do not implement the methods of the RemoteUserAdapter!
 *
 * @author Martin Gräßlin <m.graesslin@dkfz-heidelberg.de>
 */
class RemoteUserService implements RemoteUserAdapter {

    static transactional = true
    @Delegate RemoteUserAdapter remoteUserAdapter
}
