package net.biomodels.jummp.webapp.remote

import net.biomodels.jummp.remote.RemoteUserAdapter
import net.biomodels.jummp.webapp.ast.RemoteService

/**
 * @short Service delegating to RemoteUserAdapter.
 *
 * Be aware: the methods are generated by the RemoteServiceTransformation!
 * Do not implement the methods of the RemoteUserAdapter!
 *
 * @author Martin Gräßlin <m.graesslin@dkfz-heidelberg.de>
 */
@RemoteService("RemoteUserAdapter")
class RemoteUserService implements RemoteUserAdapter {

    static transactional = true
    RemoteUserAdapter remoteUserAdapter
}
