package net.biomodels.jummp.webapp.remote

import net.biomodels.jummp.remote.RemoteModelAdapter
import net.biomodels.jummp.webapp.ast.RemoteService

/**
 * @short Delegating Service to RemoteModelAdapter.
 *
 * Be aware: the methods are generated by the RemoteServiceTransformation!
 * Do not implement the methods of the RemoteModelAdapter!
 */
@RemoteService("RemoteModelAdapter")
class RemoteModelService implements RemoteModelAdapter {

    static transactional = true
    RemoteModelAdapter remoteModelAdapter
}
