package org.codehaus.groovy.grails.plugins.springsecurity.acl

/**
 * This class has been aut-generated by the Spring Security ACL plugin.
 * See http://burtbeckwith.github.com/grails-spring-security-acl/docs/manual/index.html
 */
class AclSid {

	String sid
	boolean principal

	@Override
	String toString() {
		"AclSid id $id, sid $sid, principal $principal"
	}

	static mapping = {
		version false
	}

	static constraints = {
		principal unique: 'sid'
		sid blank: false, size: 1..255
	}
}
