package net.biomodels.jummp.plugins.security

/**
 * This class has been aut-generated by the Spring Security Core plugin.
 * See http://burtbeckwith.github.com/grails-spring-security-core/
 */
class User implements Serializable {
    private static final long serialVersionUID = 1L

    String username
    String password
    String userRealName
    String email
    Boolean enabled
    Boolean accountExpired
    Boolean accountLocked
    Boolean passwordExpired

    static constraints = {
        username(blank: false, unique: true)
        password(blank: false)
        userRealName(blank: false)
        email(email: true)
    }

    static mapping = {
        password(column: '`password`')
    }

    Set<Role> getAuthorities() {
        UserRole.findAllByUser(this).collect { it.role } as Set
    }

    /**
     *
     * @return User without any security relevant information.
     */
    User sanitizedUser() {
        return new User(id: this.id, username: this.username, userRealName: this.userRealName, email: this.email)
    }
}
