// locations to search for config files that get merged into the main config
// config files can either be Java properties files or ConfigSlurper scripts

// grails.config.locations = [ "classpath:${appName}-config.properties",
//                             "classpath:${appName}-config.groovy",
//                             "file:${userHome}/.grails/${appName}-config.properties",
//                             "file:${userHome}/.grails/${appName}-config.groovy"]

// if(System.properties["${appName}.config.location"]) {
//    grails.config.locations << "file:" + System.properties["${appName}.config.location"]
// }

grails.project.groupId = appName // change this to alter the default package name and Maven publishing destination
grails.mime.file.extensions = true // enables the parsing of file extensions from URLs into the request format
grails.mime.use.accept.header = false
grails.mime.types = [ html: ['text/html','application/xhtml+xml'],
                      xml: ['text/xml', 'application/xml'],
                      text: 'text/plain',
                      js: 'text/javascript',
                      rss: 'application/rss+xml',
                      atom: 'application/atom+xml',
                      css: 'text/css',
                      csv: 'text/csv',
                      all: '*/*',
                      json: ['application/json','text/json'],
                      form: 'application/x-www-form-urlencoded',
                      multipartForm: 'multipart/form-data'
                    ]

// URL Mapping Cache Max Size, defaults to 5000
//grails.urlmapping.cache.maxsize = 1000

// The default codec used to encode data with ${}
grails.views.default.codec = "none" // none, html, base64
grails.views.gsp.encoding = "UTF-8"
grails.views.javascript.library="jquery"
grails.converters.encoding = "UTF-8"
// enable Sitemesh preprocessing of GSP pages
grails.views.gsp.sitemesh.preprocess = true
// scaffolding templates configuration
grails.scaffolding.templates.domainSuffix = 'Instance'

// Set to false to use the new Grails 1.2 JSONBuilder in the render method
grails.json.legacy.builder = false
// enabled native2ascii conversion of i18n properties files
grails.enable.native2ascii = true
// whether to install the java.util.logging bridge for sl4j. Disable for AppEngine!
grails.logging.jul.usebridge = true
// packages to include in Spring bean scanning
grails.spring.bean.packages = []

// set per-environment serverURL stem for creating absolute links
environments {
    production {
        grails.serverURL = "http://www.changeme.com"
    }
    development {
        grails.serverURL = "http://localhost:8080/${appName}"
    }
    test {
        grails.serverURL = "http://localhost:8080/${appName}"
    }

}

// log4j configuration
log4j = {
    // Example of changing the log pattern for the default console
    // appender:
    //
    //appenders {
    //    console name:'stdout', layout:pattern(conversionPattern: '%c{2} %m%n')
    //}

    error  'org.codehaus.groovy.grails.web.servlet',  //  controllers
           'org.codehaus.groovy.grails.web.pages', //  GSP
           'org.codehaus.groovy.grails.web.sitemesh', //  layouts
           'org.codehaus.groovy.grails.web.mapping.filter', // URL mapping
           'org.codehaus.groovy.grails.web.mapping', // URL mapping
           'org.codehaus.groovy.grails.commons', // core / classloading
           'org.codehaus.groovy.grails.plugins', // plugins
           'org.codehaus.groovy.grails.orm.hibernate', // hibernate integration
           'org.springframework',
           'org.hibernate',
           'net.sf.ehcache.hibernate'

    warn   'org.mortbay.log'
    appenders {
        // file appender that writes out the URLs of the Google Chart API graphs generated by the performanceGraphAppender
        def performanceGraphFileAppender = new org.apache.log4j.FileAppender(
            fileName: "log/perfGraphs.log",
            layout: pattern(conversionPattern: '%m%n')
        )
        appender name: 'performanceGraphFileAppender', performanceGraphFileAppender

        // this appender creates the Google Chart API graphs
        def performanceGraphAppender = new org.perf4j.log4j.GraphingStatisticsAppender(
            graphType: 'Mean',      // possible options: Mean, Min, Max, StdDev, Count or TPS
            tagNamesToGraph: 'tag1,tag2,tag3',
            dataPointsPerGraph: 5
        )
        performanceGraphAppender.addAppender(performanceGraphFileAppender)
        appender name: 'performanceGraph', performanceGraphAppender


        // file appender that writes out the textual, aggregated performance stats generated by the performanceStatsAppender
        def performanceStatsFileAppender = new org.apache.log4j.FileAppender(
            fileName: "log/perfStats.log",
            layout: pattern(conversionPattern: '%m%n')  // alternatively use the StatisticsCsvLayout to generate CSV
        )
        appender name: 'performanceStatsFileAppender', performanceStatsFileAppender


        // this is the most important appender and first in the appender chain. it aggregates all profiling data withing a certain time frame.
        // the GraphingStatisticsAppender is attached as a child to this appender and uses its aggregated data.
        def performanceStatsAppender = new org.perf4j.log4j.AsyncCoalescingStatisticsAppender(
            timeSlice: 10000    // ms
        )
        performanceStatsAppender.addAppender(performanceStatsFileAppender)
        performanceStatsAppender.addAppender(performanceGraphAppender)
        appender name: 'performanceStatsAppender', performanceStatsAppender
    }

    // configure the performanceStatsAppender to log at INFO level
    info   performanceStatsAppender: 'org.perf4j.TimingLogger'
}

grails.plugins.springsecurity.providerNames = ['remoteAuthenticationProvider', 'anonymousAuthenticationProvider', 'rememberMeAuthenticationProvider']
grails.plugins.springsecurity.successHandler.alwaysUseDefault = true

// theme name loaded from external configuration file
Properties jummpProperties = new Properties()
try {
    jummpProperties.load(new FileInputStream(System.getProperty("user.home") + System.getProperty("file.separator") + ".jummp.properties"))
} catch (Exception e) {
    // ignore
}
if (jummpProperties.containsKey("jummp.theme")) {
    net.biomodels.jummp.webapp.theme = jummpProperties.getProperty("jummp.theme")
    // TODO: verify if it exists
} else {
    net.biomodels.jummp.webapp.theme = "smoothness"
}

jummp.plugin.dbus.remote = false
jummp.plugin.jms.remote = true
if (jummpProperties.containsKey("jummp.remote")) {
    net.biomodels.jummp.webapp.remote = jummpProperties.getProperty("jummp.remote")
    if (jummpProperties.getProperty("jummp.remote") != "jms") {
        jms.disabled = true
        jummp.plugin.dbus.remote = true
        jummp.plugin.jms.remote = false
    }
} else {
    net.biomodels.jummp.webapp.remote = "jms"
}

// TODO: externalize the prefered MIRIAM resources
// format: key == datatype, value == resource
jummp.webapp.miriam.prefered = [
        "MIR:00000007": "MIR:00100006",
        "MIR:00000111": "MIR:00100144",
        "MIR:00000002": "MIR:00100009",
        "MIR:00000021": "MIR:00100030",
        "MIR:00000019": "MIR:00100010",
        "MIR:00000003": "MIR:00100011",
        "MIR:00000069": "MIR:00100099",
        "MIR:00000004": "MIR:00100001",
        "MIR:00000067": "MIR:00100097",
        "MIR:00000022": "MIR:00100012",
        "MIR:00000009": "MIR:00100016",
        "MIR:00000010": "MIR:00100017",
        "MIR:00000011": "MIR:00100018",
        "MIR:00000043": "MIR:00100071",
        "MIR:00000013": "MIR:00100021",
        "MIR:00000116": "MIR:00100149",
        "MIR:00000012": "MIR:00100020",
        "MIR:00000014": "MIR:00100022",
        "MIR:00000016": "MIR:00100024",
        "MIR:00000060": "MIR:00100088",
        "MIR:00000017": "MIR:00100025",
        "MIR:00000056": "MIR:00100084",
        "MIR:00000034": "MIR:00100059",
        "MIR:00000015": "MIR:00100032",
        "MIR:00000018": "MIR:00100026",
        "MIR:00000086": "MIR:00100117",
        "MIR:00000038": "MIR:00100063",
        "MIR:00000006": "MIR:00100019",
        "MIR:00000005": "MIR:00100004",
        "MIR:00000112": "MIR:00100145"
]

// fails the ant build script
grails.enable.native2ascii=false
