package net.biomodels.jummp.webapp.ast

import java.lang.annotation.Retention
import java.lang.annotation.RetentionPolicy
import java.lang.annotation.Target
import java.lang.annotation.ElementType

/**
 * @short Marker annotation for methods whose code needs to be generated by the @link DBusAdapterTransformation.
 * The annotation can only be used in classes which are annotated with the @link DBusAdapter annotation
 *
 * @see DBusAdapter
 * @see DBusAdapterTransformation
 * @author Martin Gräßlin <m.graesslin@dkfz.de>
 */
@Retention(RetentionPolicy.SOURCE)
@Target([ElementType.METHOD])
public @interface DBusMethod {
    boolean isAuthenticate() default false
    boolean isAnonymous() default false
    String delegate() default ""
}
