package net.biomodels.jummp.webapp.ast

import java.lang.annotation.ElementType
import java.lang.annotation.Retention
import java.lang.annotation.RetentionPolicy
import java.lang.annotation.Target
import org.codehaus.groovy.transform.GroovyASTTransformationClass

/**
 * @short Marker Annotation to trigger a @link RemoteServiceTransformation.
 *
 * The annotation may only be used for classes and it triggers an AST Transformation.
 * As a value the annotation expects the name of the Interface for which methods shold
 * be generated by the AST Transformation.
 *
 * @see RemoteServiceTransformation
 * @author Martin Gräßlin <m.graesslin@dkfz.de>
 */
@Retention(RetentionPolicy.SOURCE)
@Target([ElementType.TYPE])
@GroovyASTTransformationClass(["net.biomodels.jummp.webapp.ast.RemoteServiceTransformation"])
public @interface RemoteService {
    String value()
}
