import org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils

/**
 * This class has been aut-generated by the Spring Security Core plugin.
 * See http://burtbeckwith.github.com/grails-spring-security-core/
 */
class LogoutController {

    /**
     * Index action. Redirects to the Spring security logout uri.
     */
    def index = {
        // TODO  put any pre-logout code here
        redirect uri: SpringSecurityUtils.securityConfig.logout.filterProcessesUrl // '/j_spring_security_logout'
    }
}
